services:
  app_bazar:
    build:
      context: ./bazar
      dockerfile: Dockerfile
    mem_limit: 512m
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:postgresql://bazar_baz:5432/bazar
      DB_USERNAME: postgres
      DB_PASSWORD: 42576661
    restart: always
    depends_on:
      bazar_baz:
        condition: service_healthy

  bazar_baz:
    image: postgres:16
    environment:
      POSTGRES_DB: bazar
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 42576661
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
